library(MASS)
iris_lda<-lda(Species~.,data=iris)
iris_lda
0.9912+0.0088
iris_lda_pred<-predict(iris_lda,iris)
iris_lda_pred

ldahist(data=iris_lda_pred$x[,1],g=iris$Species)
ld<-data.frame(iris$Species,iris_lda_pred$class)
View(ld)
library(caret)
confusionMatrix(iris$Species,iris_lda_pred$class)
##############################################################
library(party)
ld1<-ctree(Species~.,data=iris)
ld1<-predict(ld1,iris)
confusionMatrix(ld1,iris$Species)
############################################################
library(randomForest)
ld2<-randomForest(Species~.,data=iris)
ld2<-predict(ld2,iris)
confusionMatrix(ld2,iris$Species)
###############################################################3